### ISSUE TITLE
随机图标的问题

### ISSUE THREAD

**Issue by TCOTC** [mozhux/Lucide-icon#2]
`随机` 用的是 `刷新` ，感觉就很奇怪：

![image](https://github.com/mozhux/Lucide-icon/assets/78434827/1effef85-1f38-4b67-ae11-6929bed9c7a9)

这种才应该是 `随机` ：

![image](https://github.com/mozhux/Lucide-icon/assets/78434827/11296d3b-0b39-4015-b121-28b2a7b86234)

**Comment by TCOTC** [comment]
刚刚发现这个确实是刷新：#iconRefresh

**Comment by mozhux** [comment]
> 刚刚发现这个确实是刷新：#iconRefresh

这个是V大那边控制的，她偷懒复用很多图标。
